version: "3.3"
services:
  backend:
    build: .
    image: nodebackend:mcc
    container_name: nodebackend
    ports:
      - "3000:3000"
#    links:
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.0
    container_name: mongo
    ports:
      - "1048:27017"
    volumes:
      - "~:/db"