openapi: 3.0.0
info:
  version: "3.0.0"
  title: "OpenApi"
servers:
  - url: "neppi-server.northeurope.cloudapp.azure.com:3000"
#  - url: "http://13.69.194.97:3000"
paths:
  /sensor:
    post:
      tags:
        - "Create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sensor"
      responses:
        201:
          description: "Sensor successfully created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Sensor successfully created"
                  id:
                    type: string
          links:
            GetSensorById:
              operationId: getSensor
              parameters:
                id: "response.body#/id"
  /sensor/{sensor_id}:
    parameters:
      - in: path
        name: sensor_id
        required: true
        schema:
          $ref: "#/components/schemas/Sensor"
    get:
      tags:
        - Read
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
          links:
            GetSensorById:
              operationId: getSensor
              parameters:
                id: "$request.path.sensor_id"
                name: "$response.body#/name"
                value: "$response.body#/value"
                status: "$response.body#/status"
    put:
      tags:
        - "Update"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sensor"
      responses:
        200:
          description: "Sensor successfully updated"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Sensor successfully updated"
                  id:
                    type: string
          links:
            GetSensorById:
              operationId: getSensor
              parameters:
                id: "$request.path.sensor_id"
                name: "$response.body#/name"
                value: "$response.body#/value"
                status: "$response.body#/status"
    delete:
      tags:
        - "Delete"
      responses:
        200:
          description: "Sensor successfully deleted"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Sensor successfully deleted"
                  id:
                    type: string
          links:
            GetSensorById:
              operationId: getSensor
              parameters:
                id: "$request.path.sensor_id"
components:
  schemas:
    Sensor:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        status:
          type: string